### ISSUE TITLE
Few bugs I've found!

### ISSUE THREAD

**Issue by TheDemystifier** [BlueGreenMagick/Review-Hotmouse#9] opened 2020-12-18 22:42 UTC
### Bug 1

Combinations I've tried that are not working:

- q_click_middle_wheel_down
- q_click_right_wheel_down

I reckon it's because you can't have any event after click, right? Then the "press -> click -> wheel" stated in the documentation should be reconsidered since wheel cannot come after click.

### Bug 2

Deleting a certain combo comes back after restarting Anki. Example, try deleting any of the default combos → Restart Anki → Combo back.

**Comment by BlueGreenMagick** [comment] 2021-08-02 18:27
Regarding bug 1, that's not a bug. You can rename it to `q_press_middle_wheel_down` and `q_press_right_wheel_down` to achieve what you want.

Bug 2 is known, but I keep postponing it because it'll be a huge undertaking to fix it :sweat_smile:. Meanwhile, you can set it to "off".

Sorry for the really late response!

**Comment by BlueGreenMagick** [comment] 2021-08-31 02:17
Bug 2 was fixed in the latest update.

**Closed by BlueGreenMagick** 2021-08-31 02:17 UTC
Labels: bug-minor
